'use client'
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../styles/globals.css";
import React, {ReactElement, useEffect, useState} from "react";

const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

const RootLayout = ({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) => {

  const [ui, setUi] = useState<React.ReactNode | null>(null);

  useEffect(() => {
    setUi(children)
  }, []);
  return (
    <html lang="en" className="bg-[#F5F7F8] ">
      <body className={`${inter.className} w-full h-screen subpixel-antialiased`}>
        {ui}
      </body>
    </html>
);
}
export default RootLayout
